# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
