# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1491277763);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1491277883);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1491277643);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1491278003);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("datareporting.sessions.current.activeTicks", 18);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2521);
user_pref("datareporting.sessions.current.main", 51);
user_pref("datareporting.sessions.current.startTime", "1491277522659");
user_pref("datareporting.sessions.current.totalTime", 2108);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1491277474392,\"a\":1,\"t\":19,\"c\":true,\"m\":1030,\"fp\":12561,\"sr\":-1}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-es-AR@thunderbird.mozilla.org\":{\"version\":\"45.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-es-ES@thunderbird.mozilla.org\":{\"version\":\"45.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"45.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1491277764);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1485374628000},\"langpack-es-AR@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485375445000},\"langpack-es-ES@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-es-ES@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485375445000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485374674000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485375443000}}}");
user_pref("idle.lastDailyNotification", 1491278642);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.displayname.version", 1);
user_pref("mail.identity.id1.compose_html", false);
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "mailbox://gatoma_95@localhost/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "mailbox://gatoma_95@localhost/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Jaret");
user_pref("mail.identity.id1.stationery_folder", "mailbox://gatoma_95@localhost/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "gatoma_95@hotmail.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.root.movemail", "/home/jaret/.thunderbird/f77ekjej.default/Mail");
user_pref("mail.root.movemail-rel", "[ProfD]Mail");
user_pref("mail.root.none", "/home/jaret/.thunderbird/f77ekjej.default/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.directory", "/home/jaret/.thunderbird/f77ekjej.default/Mail/Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.name", "Carpetas locales");
user_pref("mail.server.server1.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.directory", "/home/jaret/.thunderbird/f77ekjej.default/Mail/localhost");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/localhost");
user_pref("mail.server.server2.download_on_biff", true);
user_pref("mail.server.server2.hostname", "localhost");
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.name", "gatoma_95@hotmail.com");
user_pref("mail.server.server2.spamActionTargetAccount", "mailbox://gatoma_95@localhost");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "movemail");
user_pref("mail.server.server2.userName", "gatoma_95");
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "3c6af959-a5e1-4df3-bcd6-f946d0b3bcd");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1491278642);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1491278642);
user_pref("toolkit.telemetry.cachedClientID", "e1ee5f64-1364-4672-b3e7-81859910742a");
user_pref("toolkit.telemetry.previousBuildID", "20170125182329");
